### ISSUE TITLE
Duplicated language utils

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/NeonCore#148]
neon_core.language and neon_utils.language_utils should be consolidated into a single location (probably neon_utils). Possibly consider moving those to a new `neon-lang-utils` package? TranslatorFactory and DetectorFactory could be useful on their own...

**Comment by NeonDaniel** [comment]
https://github.com/NeonGeckoCom/neon-skill-utils/pull/208

**Comment by JarbasAl** [comment]
maybe we should move the factories into ovos plugin manager like ovos-core is doing?

they become simpler also, because they keep strings with plugin name instead of references

**Comment by NeonDaniel** [comment]
Not sure about the factories if they're still NeonCore-specific, but the base classes I think make sense in OPM
