### ISSUE TITLE
Define 'stop' for multi-user environments

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/NeonCore#199]
## Objective
Define implementation of 'stop' command for multiple users

## Initial Implementation
- [ ] Ensure enough context is included in `stop` Messages to identify the requesting user/client
- [ ] Ensure `stop` callback in skills are updated to account for multiple users
- [ ] Add some client-side handling to stop media playback, etc.

## Open Issues
- [ ] What elements are "globally" stopped? (audio playback)
- [ ] What does skills backwards-compatibility look like?
- [ ] Is 'stop' user-specific or client-specific (or both)

**Comment by JarbasAl** [comment]
FWIW this is mostly implemented in OVOS https://github.com/OpenVoiceOS/ovos-core/pull/391

Neon users just need to track their own session_id
