### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by Miroslave11** [NeonGeckoCom/NeonCore#328]
Hi,
during installation I got the belom mentioned error.
It was Installing Neon in a User/Deployment Environment.

Collecting psutil~=5.6
  Downloading psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
ERROR: Could not find a version that satisfies the requirement neon-transcripts-controller (unavailable) (from neon-core[client,core-modules,remote]) (from versions: none)
ERROR: No matching distribution found for neon-transcripts-controller (unavailable)
setup.sh: line 343: neon-config-import: command not found
setup.sh: line 418: neon-install-default-skills: command not found
Setup Complete
root@linux:/home/user# 

Can you please help how to solve it?

**Comment by NeonDaniel** [comment]
Sorry I missed this, and I think I replied in chat but posting here just in case:

Looks like there are some private dependencies listed in the `client` and `dev` extras. I'm aiming for another stable release this week and I'll remove those for that release. For now, you should be able to install without those options and then manually install these dependencies:

```
ovos-ww-plugin-vosk~=0.0,>=0.0.4
neon-cli-client~=0.2
neon-mana-utils~=0.0,>=0.0.3
```

You may also find it easier to run the Docker setup (https://github.com/NeonGeckoCom/NeonCore#quick-start)
