### ISSUE TITLE
[BUG] Wallpaper(s) are not being rotated through

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/NeonCore#666]
### Description

I only get one homescreen/wallpaper ; even though menu/settings/display/wallpaper rotation is set to 'on'

### Steps to Reproduce

select the pull-down-menu/settings/display/wallpaper rotation is set to 'on' 
back out and then wait for rotation - doesn't happen

### Other Notes

os 24-5-2 base , but also dev images .2b2; .6b3, 7b4

**Comment by NeonDaniel** [comment]
Probably related to https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wallpaper-manager . Need to further diagnose the issue to confirm

**Comment by Olzeke51** [comment]
here are the log files with DEBUG set:  
the file wallpaper_bus.log is a collection of any line with 'wallpaper' in it. - I turned OFF the rotation, but noted later is was back ON. (my actions are explained at the top of that file)
Also the archive of all the logs.
[wallpaper_bus.log](https://github.com/NeonGeckoCom/NeonCore/files/15462496/wallpaper_bus.log)
[wallpaper_logs.tar.gz](https://github.com/NeonGeckoCom/NeonCore/files/15462497/wallpaper_logs.tar.gz)

**Comment by Olzeke51** [comment]
was scanning a recent journalctl log and noticed this :
Jun 08 05:12:55 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:13:23 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:13:51 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:14:18 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:14:46 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:15:14 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:15:41 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:16:09 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
Jun 08 05:16:36 neon ovos-shell[743]: file:///home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/idle.qml:178: TypeError: Value is null and could not be converted to an object
```
HTH - Gary

systemd logging (other than booting mssgs) started _Jun 08 03:05:01 neon systemd-journald[350]:_

**Comment by NeonDaniel** [comment]
Issue moved to https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wallpaper-manager/issues/9
