### ISSUE TITLE
[BUG] ovos-PHAL-plugin-mk1 installed on Mark 2 image

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/NeonCore#686]
### Description

The ovos-PHAL-plugin-mk1 plugin is getting installed on a Mark 2, which isn't terrible, but does pollute the PHAL logs unnecessarily.

### Steps to Reproduce

- Run a Mark 2 Neon image
- `pip list | grep -i ovos-PHAL-plugin-mk1`

**Comment by NeonDaniel** [comment]
The "Mark 2" image is really just the RPi image, so by default I have that plugin installed and disabled by default. Is it just logging that it is disabled, or is it trying to load?

**Comment by mikejgray** [comment]
> The "Mark 2" image is really just the RPi image, so by default I have that plugin installed and disabled by default. Is it just logging that it is disabled, or is it trying to load?

It's trying to load, you can see it in the PHAL logs

**Comment by NeonDaniel** [comment]
Looks like a typo in the plugin name; I'll PR a fix today

**Comment by NeonDaniel** [comment]
I see that disabling a plugin that has a validator method isn't working in upstream PHAL, sending a PR there
